"""create delivery agents table

Revision ID: 5e203cfc19f9
Revises: 938683be9e10
Create Date: 2026-10-02 13:21:32.463252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e203cfc19f9'
down_revision: Union[str, Sequence[str], None] = '938683be9e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_agents_employee_code'), 'delivery_agents', ['employee_code'], unique=True)
    op.create_index(op.f('ix_delivery_agents_id'), 'delivery_agents', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_agents_user_id'), 'delivery_agents', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_agents_user_id'), table_name='delivery_agents')
    op.drop_index(op.f('ix_delivery_agents_id'), table_name='delivery_agents')
    op.drop_index(op.f('ix_delivery_agents_employee_code'), table_name='delivery_agents')
    op.drop_table('delivery_agents')
    # ### end Alembic commands ###
