"""add webhooks

Revision ID: 7ac0dc910043
Revises: 256b6c1996a1
Create Date: 2026-10-02 14:37:23.793513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac0dc910043'
down_revision: Union[str, Sequence[str], None] = '256b6c1996a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_carrier_id'), 'webhooks', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_webhooks_event_type'), 'webhooks', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhooks_external_event_id'), 'webhooks', ['external_event_id'], unique=True)
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_webhooks_shipment_id'), 'webhooks', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_webhooks_status'), 'webhooks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_status'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_shipment_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_external_event_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_event_type'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_carrier_id'), table_name='webhooks')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
