"""add delivery attempts

Revision ID: 82a90ead6b5e
Revises: 8b9a0a8535c0
Create Date: 2026-10-02 13:49:53.627431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a90ead6b5e'
down_revision: Union[str, Sequence[str], None] = '8b9a0a8535c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('delivery_agent_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agents.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_delivery_agent_id'), 'delivery_attempts', ['delivery_agent_id'], unique=False)
    op.create_index(op.f('ix_delivery_attempts_id'), 'delivery_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_attempts_shipment_id'), 'delivery_attempts', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_attempts_shipment_id'), table_name='delivery_attempts')
    op.drop_index(op.f('ix_delivery_attempts_id'), table_name='delivery_attempts')
    op.drop_index(op.f('ix_delivery_attempts_delivery_agent_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    # ### end Alembic commands ###
