"""create shipment assignments table

Revision ID: 8b9a0a8535c0
Revises: 5e203cfc19f9
Create Date: 2026-10-02 13:35:04.480878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9a0a8535c0'
down_revision: Union[str, Sequence[str], None] = '5e203cfc19f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('delivery_agent_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agents.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_assignments_delivery_agent_id'), 'shipment_assignments', ['delivery_agent_id'], unique=False)
    op.create_index(op.f('ix_shipment_assignments_id'), 'shipment_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_assignments_shipment_id'), 'shipment_assignments', ['shipment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_assignments_shipment_id'), table_name='shipment_assignments')
    op.drop_index(op.f('ix_shipment_assignments_id'), table_name='shipment_assignments')
    op.drop_index(op.f('ix_shipment_assignments_delivery_agent_id'), table_name='shipment_assignments')
    op.drop_table('shipment_assignments')
    # ### end Alembic commands ###
