"""add proof of delivery

Revision ID: e2ea7b02b99a
Revises: 82a90ead6b5e
Create Date: 2026-10-02 13:56:28.419429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ea7b02b99a'
down_revision: Union[str, Sequence[str], None] = '82a90ead6b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proof_of_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('delivery_attempt_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=150), nullable=False),
    sa.Column('signature_reference', sa.String(length=500), nullable=True),
    sa.Column('photo_reference', sa.String(length=500), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_attempt_id'], ['delivery_attempts.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_of_deliveries_delivery_attempt_id'), 'proof_of_deliveries', ['delivery_attempt_id'], unique=True)
    op.create_index(op.f('ix_proof_of_deliveries_id'), 'proof_of_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_proof_of_deliveries_shipment_id'), 'proof_of_deliveries', ['shipment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proof_of_deliveries_shipment_id'), table_name='proof_of_deliveries')
    op.drop_index(op.f('ix_proof_of_deliveries_id'), table_name='proof_of_deliveries')
    op.drop_index(op.f('ix_proof_of_deliveries_delivery_attempt_id'), table_name='proof_of_deliveries')
    op.drop_table('proof_of_deliveries')
    # ### end Alembic commands ###
