"""add shipment exceptions

Revision ID: e96c9ab770dd
Revises: e2ea7b02b99a
Create Date: 2026-10-02 14:02:03.925053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96c9ab770dd'
down_revision: Union[str, Sequence[str], None] = 'e2ea7b02b99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('exception_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_exceptions_exception_type'), 'shipment_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_id'), 'shipment_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_reported_by'), 'shipment_exceptions', ['reported_by'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_shipment_id'), 'shipment_exceptions', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_status'), 'shipment_exceptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_exceptions_status'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_shipment_id'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_reported_by'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_id'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_exception_type'), table_name='shipment_exceptions')
    op.drop_table('shipment_exceptions')
    # ### end Alembic commands ###
