from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    OPERATIONS_MANAGER = "OPERATIONS_MANAGER"
    WAREHOUSE_STAFF = "WAREHOUSE_STAFF"
    DELIVERY_AGENT = "DELIVERY_AGENT"
    CUSTOMER = "CUSTOMER"
    API_CLIENT = "API_CLIENT"