from enum import Enum


class ShipmentStatus(str, Enum):
    CREATED = "CREATED"
    CONFIRMED = "CONFIRMED"
    PICKUP_SCHEDULED = "PICKUP_SCHEDULED"
    PICKED_UP = "PICKED_UP"
    AT_ORIGIN_WAREHOUSE = "AT_ORIGIN_WAREHOUSE"
    IN_TRANSIT = "IN_TRANSIT"
    AT_DESTINATION_WAREHOUSE = "AT_DESTINATION_WAREHOUSE"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"

    CANCELLED = "CANCELLED"
    ON_HOLD = "ON_HOLD"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    RETURN_INITIATED = "RETURN_INITIATED"
    RETURNED = "RETURNED"
    LOST = "LOST"
    DAMAGED = "DAMAGED"